stages:
  - test

before_script:
  - apt-get update -qq
  - apt-get install -qy libelf1
  - npm install --global npm
  - npm install

Test Node:4:
  stage: test
  image: 'node:4'
  script:
    - npm test

Test Node:6:
  stage: test
  image: 'node:6'
  script:
    - npm test

Test Node:7:
  stage: test
  image: 'node:7'
  script:
    - npm test
